services:
  - type: web
    name: matrixcalc
    env: docker
    repo: https://github.com/Medalcode/Matrixcalc
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DEBUG
        value: 'False'
      - key: RUN_SCHEDULER
        value: 'False'
