services:
  - type: web
    name: matrixcalc
    env: docker
    repo: https://github.com/Medalcode/Matrixcalc
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: matrixcalc-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DEBUG
        value: 'False'
      - key: RUN_SCHEDULER
        value: 'False'

databases:
  - name: matrixcalc-db
    plan: free
    region: oregon
    databaseName: matrixcalc
    user: matrixcalc
    ipAllowList: []
