# Generated by Django 4.2.27 on 2025-12-21 05:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la matriz', max_length=200)),
                ('rows', models.PositiveIntegerField(help_text='Número de filas', validators=[django.core.validators.MinValueValidator(1)])),
                ('cols', models.PositiveIntegerField(help_text='Número de columnas', validators=[django.core.validators.MinValueValidator(1)])),
                ('data', models.JSONField(help_text='Datos de la matriz como lista de listas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matriz',
                'verbose_name_plural': 'Matrices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('SUM', 'Suma'), ('SUBTRACT', 'Resta'), ('MULTIPLY', 'Multiplicación'), ('INVERSE', 'Inversa'), ('DETERMINANT', 'Determinante'), ('TRANSPOSE', 'Transpuesta')], help_text='Tipo de operación realizada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time_ms', models.PositiveIntegerField(help_text='Tiempo de ejecución en milisegundos')),
                ('matrix_a', models.ForeignKey(help_text='Primera matriz operando', on_delete=django.db.models.deletion.CASCADE, related_name='operations_as_a', to='calculator.matrix')),
                ('matrix_b', models.ForeignKey(blank=True, help_text='Segunda matriz operando (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_as_b', to='calculator.matrix')),
                ('result', models.ForeignKey(help_text='Matriz resultado', on_delete=django.db.models.deletion.CASCADE, related_name='operations_as_result', to='calculator.matrix')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='matrix',
            index=models.Index(fields=['created_at'], name='calculator__created_d9ef65_idx'),
        ),
        migrations.AddIndex(
            model_name='matrix',
            index=models.Index(fields=['name'], name='calculator__name_7651e0_idx'),
        ),
        migrations.AddIndex(
            model_name='matrix',
            index=models.Index(fields=['-created_at'], name='calculator__created_950953_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_type'], name='calculator__operati_f7fa02_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['created_at'], name='calculator__created_2e6f42_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['-created_at'], name='calculator__created_90b3e3_idx'),
        ),
    ]
