# Generated by Django 4.2.27 on 2026-01-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Datos adicionales o referencias a otras matrices resultado (ej: SVD components)', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('SUM', 'Suma'), ('SUBTRACT', 'Resta'), ('MULTIPLY', 'Multiplicación'), ('INVERSE', 'Inversa'), ('DETERMINANT', 'Determinante'), ('TRANSPOSE', 'Transpuesta'), ('RANK', 'Rango'), ('EIGEN', 'Valores/Vectores Propios'), ('SVD', 'Descomposición Valor Singular'), ('QR', 'Descomposición QR'), ('LU', 'Descomposición LU'), ('CHOLESKY', 'Descomposición Cholesky')], help_text='Tipo de operación realizada', max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='result',
            field=models.ForeignKey(help_text='Matriz resultado principal', on_delete=django.db.models.deletion.CASCADE, related_name='operations_as_result', to='calculator.matrix'),
        ),
    ]
