#!/bin/bash

# ========================================
# MatrixCalc v2.0 - Deploy Instructions
# ========================================

echo "📋 INSTRUCCIONES PARA DESPLEGAR A CLOUD RUN"
echo ""
echo "Este script no puede ejecutarse automáticamente porque gcloud no está instalado"
echo "en este entorno. Sigue estos pasos en tu máquina local o Cloud Shell:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 PASO 1: Preparar el Código"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1.1. Commit todos los cambios:"
echo ""
echo "    git status"
echo "    git add ."
echo "    git commit -m \"feat: add dark mode, toasts, templates and all v2.0 improvements\""
echo "    git push"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 PASO 2: Obtener URL del Backend Actual"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ejecuta este comando para obtener la URL de tu backend:"
echo ""
echo "    gcloud run services describe matrixcalc-backend \\"
echo "      --region=us-central1 \\"
echo "      --format=\"value(status.url)\""
echo ""
echo "Copia la URL que te devuelve (ejemplo: https://matrixcalc-backend-xxx.run.app)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 PASO 3: Configurar Frontend"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Reemplaza [BACKEND_URL] con la URL que obtuviste:"
echo ""
echo "    echo \"VITE_API_URL=https://[BACKEND_URL]/api\" > frontend/.env.production"
echo ""
echo "Ejemplo:"
echo "    echo \"VITE_API_URL=https://matrixcalc-backend-xxx.run.app/api\" > frontend/.env.production"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 PASO 4: Deploy Frontend (Solo UI Changes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Si solo quieres actualizar el frontend con las mejoras de UI:"
echo ""
echo "    cd /ruta/a/Matrixcalc"
echo "    gcloud run deploy matrixcalc-frontend \\"
echo "      --source=. \\"
echo "      --region=us-central1 \\"
echo "      --platform=managed \\"
echo "      --allow-unauthenticated"
echo ""
echo "Tiempo estimado: 5-8 minutos"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 PASO 5 (OPCIONAL): Deploy Backend + Frontend"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Si quieres actualizar backend y frontend (deploy completo):"
echo ""
echo "    gcloud builds submit \\"
echo "      --config=cloudbuild.yaml \\"
echo "      --substitutions=_REGION=us-central1,_REPOSITORY=matrixcalc"
echo ""
echo "Tiempo estimado: 10-15 minutos"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 PASO 6: Verificar Deploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Obtener URL del frontend:"
echo ""
echo "    gcloud run services describe matrixcalc-frontend \\"
echo "      --region=us-central1 \\"
echo "      --format=\"value(status.url)\""
echo ""
echo "Abre la URL en tu navegador y verifica:"
echo ""
echo "  ✅ Dark mode toggle en la navegación"
echo "  ✅ /calculator → Templates visibles"
echo "  ✅ Crear matriz → Toast de confirmación"
echo "  ✅ /stats → Gráficos cargando"
echo "  ✅ /about → Página con contenido"
echo "  ✅ /docs → Documentación completa"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 RESUMEN DE ARCHIVOS MODIFICADOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Nuevos componentes (8):"
echo "  • ToastContainer.vue"
echo "  • ThemeToggle.vue"
echo "  • LoadingSpinner.vue"
echo "  • ConfirmationModal.vue"
echo "  • DocsView.vue"
echo ""
echo "Nuevos composables (3):"
echo "  • useToast.ts"
echo "  • useTheme.ts"
echo "  • useConfirmation.ts"
echo ""
echo "Nuevas utilidades (1):"
echo "  • matrixTemplates.ts (14 templates)"
echo ""
echo "Componentes mejorados (5):"
echo "  • App.vue (dark mode + toasts)"
echo "  • MatrixEditor.vue (templates + toasts)"
echo "  • MatrixList.vue (modal + toasts)"
echo "  • OperationPanel.vue (validaciones)"
echo "  • BackupManager.vue (UI renovada)"
echo ""
echo "Vistas mejoradas (2):"
echo "  • HomeView.vue (dark mode)"
echo "  • AboutView.vue (dark mode)"
echo ""
echo "Configuración (2):"
echo "  • tailwind.config.js (darkMode: 'class')"
echo "  • router/index.ts (rutas /about y /docs)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 TIPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "• Si solo cambiaste el frontend, solo deploy frontend (PASO 4)"
echo "• El backend no cambió, así que puedes omitir su deploy"
echo "• Las URLs se mantienen igual → No hay downtime"
echo "• Puedes hacer rollback si algo falla"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 COMANDO RECOMENDADO (Frontend Only)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Como solo mejoramos el frontend, ejecuta:"
echo ""
echo "# 1. Configurar backend URL"
echo "BACKEND_URL=\$(gcloud run services describe matrixcalc-backend --region=us-central1 --format=\"value(status.url)\")"
echo "echo \"VITE_API_URL=\${BACKEND_URL}/api\" > frontend/.env.production"
echo ""
echo "# 2. Deploy frontend"
echo "gcloud run deploy matrixcalc-frontend --source=. --region=us-central1 --allow-unauthenticated"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ ¡TODO LISTO PARA DEPLOY!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
